package main

import (
	"fmt"
	"io/ioutil"
	"os"
	"regexp"
	"strings"
)

var tmpl = `//WARNING: This file is automatically generated.
package main
//go:generate go run static/pack_assets.go

var assetCSS = `

func main() {
	err := run()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	//read CSS file
	cssBytes, err := ioutil.ReadFile("static/style.css")
	if err != nil {
		return err
	}
	cssText := string(cssBytes)

	//compress all whitespace to single spaces
	cssText = regexp.MustCompile(`\s+`).ReplaceAllString(cssText, " ")
	//remove all whitespaces where there is a non-word character on either side
	cssText = regexp.MustCompile(`(\W) `).ReplaceAllString(cssText, "$1")
	cssText = regexp.MustCompile(`(\w) (\W)`).ReplaceAllString(cssText, "$1$2")
	//remove redundant semicolon
	cssText = strings.Replace(cssText, ";}", "}", -1)

	//make source file
	text := tmpl + "`" + cssText + "`"
	return ioutil.WriteFile("assets.go", []byte(text), 0644)
}
